// clientes/livros-next/pages/LivroLista.tsx
import type { NextPage } from "next";
import React, { useEffect, useState } from "react";
import styles from "../styles/Home.module.css"
import { Livro } from "@/classes/modelo/Livro";
import { LinhaLivro } from "@/componentes/LinhaLivro";
import { Menu } from "@/componentes/Menu";
import Head from "next/head";
import { ControleLivros } from "@/classes/controle/ControleLivros";

const LivroLista: NextPage = () => {
    const [livros, setLivros] = useState<Array<Livro>>([]);
    const [carregado, setCarregado] = useState(false);
    const controleLivros = new ControleLivros();

    useEffect(() => {
        controleLivros.obterLivros().then((livros) => {
            setLivros(livros);
            setCarregado(true);
        });
    }, [carregado]);

    const excluir = async (codigo: string) => {
        await controleLivros.excluir(codigo)
        .then(() => {
            setCarregado(false);
        });        
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Loja Next</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Menu />
            <main className={`${styles.main}`}>
                <h1 className={`${styles.title} display-2`}>Catálogo</h1>
                <table className="table table-striped">
                    <thead className="table-dark">
                        <tr>
                            <th scope="col" className="col-2">Título</th>
                            <th scope="col">Resumo</th>
                            <th scope="col" className="col-2">Editora</th>
                            <th scope="col" className="col-2">Autores</th>
                        </tr>
                    </thead>
                    <tbody>
                        {livros.map((livro, index) => (
                            <LinhaLivro key={index} livro={livro} excluir={() => excluir(livro.codigo)} />
                        ))}
                    </tbody>
                </table>
            </main>
        </div>
    );
};

export default LivroLista;

// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  editoras: Array<Editora> = [];
  livros: Array<Livro> = [];

  constructor(private servEditora: ControleEditoraService, private servLivros: ControleLivrosService) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().then(livros => {
      this.livros = livros;
    });
  }

  excluir = (codLivro: string): void => {
    this.servLivros.excluir(codLivro).then(() => {
      this.servLivros.obterLivros().then(livros => {
        this.livros = livros;
      });
    });
  }

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<main class="container">
    <h1>Catálogo de Livros</h1>  
    <table class="table table-striped">
      <thead class="table-dark">
        <tr>
          <th scope="col" class="col-2">Título</th>
          <th>Resumo</th>
          <th>Editora</th>
          <th>Autores</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let livro of livros">
          <td>{{ livro.titulo }}
            <button class="btn btn-danger d-block btn-sm" (click)="excluir(livro.codigo)">Excluir</button>
          </td>
          <td>{{livro.resumo}}</td>
          <td>{{ obterNome(livro.codEditora) }}</td>
          <td>
            <ul>
              <li *ngFor="let autor of livro.autores">{{ autor }}</li>
            </ul>
          </td>
        </tr>
      </tbody>
    </table>
  </main>
