// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  livro: Livro;
  autoresForm: string = '';
  editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {
    this.livro = new Livro('', 0, '', '', []);
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/lista');
    });
  }
}
<main class="container">
    <h1>Dados do Livro</h1>  
    <form (submit)="incluir()" ngNativeValidate>
      <div class="form-group">
        <label for="titulo">Título:</label>
        <input type="text" name="titulo" class="form-control" required [(ngModel)]="livro.titulo">
      </div>  
      <div class="form-group">
        <label for="resumo">Resumo:</label>
        <textarea name="resumo" class="form-control" [(ngModel)]="livro.resumo"></textarea>
      </div>  
      <div class="form-group">
        <label for="editora">Editora:</label>
        <select name="editora" class="form-select" required [(ngModel)]="livro.codEditora">
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>
      </div>  
      <div class="form-group">
        <label>Autores:</label>
        <textarea name="autores" class="form-control" [(ngModel)]="autoresForm"></textarea>
      </div>  
      <button type="submit" class="btn btn-primary d-block mt-3">Salvar</button>
    </form>
  </main>

// clientes/livros-next/pages/LivroDados.tsx
import type { NextPage } from "next";
import React from "react";
import { useState } from "react";
import styles from "../styles/Home.module.css"
import { ControleEditora } from "@/classes/controle/ControleEditora";
import { ControleLivros } from "@/classes/controle/ControleLivros";
import { Livro } from "@/classes/modelo/Livro";
import { Menu } from "@/componentes/Menu";
import Head from "next/head";
import { Editora } from "@/classes/modelo/Editora";
import { useRouter } from "next/router";

const LivroDados: NextPage = () => {
    const controleEditora = new ControleEditora();
    const controleLivros = new ControleLivros();
    
    const opcoes = controleEditora.getEditoras().map((editora: Editora) => ({
        value: editora.codEditora,
        text: editora.nome}));
    const [titulo, setTitulo] = useState("");
    const [resumo, setResumo] = useState("");
    const [autores, setAutores] = useState("");
    const [codEditora, setCodEditora] = useState(opcoes[0].value);
    const router = useRouter();

    const tratarCombo = (event: React.ChangeEvent<HTMLSelectElement>) =>{
        setCodEditora(Number(event.target.value));        
    };

    const incluir = async (event: React.FormEvent<HTMLFormElement>) =>{
        event.preventDefault();
        const livro: Livro ={
            codigo: "",
            titulo: titulo,
            resumo: resumo,            
            codEditora: codEditora,
            autores: autores.split("\n")
        };
        controleLivros.incluir(livro)
            .then(() => {
                router.push("/LivroLista");
            })
            .catch((error) => {
                console.error("Erro ao incluir livro:", error);
            });
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Loja Next</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Menu />
            <main className={`${styles.main}`}>
                <h1 className="display-2">Dados do Livro</h1>
                <form onSubmit={incluir}>
                    <div className="row">
                        <label>Título
                        <input type="text" className="form-control" value={titulo} onChange={(evento) => setTitulo(evento.target.value)}></input>
                        </label>
                        <label>Resumo
                        <textarea value={resumo} className="form-control" onChange={(evento) => setResumo(evento.target.value)}></textarea>
                        </label>
                        <label>Editora
                        <select className="form-select" value={codEditora} onChange={tratarCombo}>
                            {opcoes.map((opcao) => (
                                <option key={opcao.value} value={opcao.value}>{opcao.text}</option>
                            ))}
                        </select>
                        </label>
                        <label>Autores
                        <textarea className="form-control" value={autores} onChange={(evento) => setAutores(evento.target.value)}></textarea>
                        </label>
                    </div>
                    <button className="btn btn-primary d-block mt-3" type="submit">Incluir</button>                    
                </form>                
            </main>
        </div>
    );
};

export default LivroDados;
