// clientes/livros-react/src/LivroDados.js
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { ControleLivros } from './controle/ControleLivros';
import { ControleEditora } from './controle/ControleEditora';

const LivroDados = () => {
  const controleLivros = new ControleLivros();
  const controleEditora = new ControleEditora();
  const opcoes = controleEditora.getEditoras().map((editora) => {
    return {
      value: editora.codEditora,
      text: editora.nome,
    };
  });

  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState(opcoes[0].value);
  const navigate = useNavigate();

  const tratarCombo = (evento) => {
    setCodEditora(Number(evento.target.value));
  };

  const incluir = (evento) => {
    evento.preventDefault();
    controleLivros
      .incluir({
        codigo: '',
        titulo: titulo,
        resumo: resumo,
        autores: autores.split('\n'),
        codEditora: codEditora,
      })
      .then(() => {
        navigate('/raiz');
      });
  };

  return (
    <main>
      <div>
        <h1>Dados do Livro</h1>
        <form onSubmit={incluir}>
          <div className="form-group">
            <label>Título</label>
            <input type="text" className="form-control" value={titulo} onChange={(evento) => setTitulo(evento.target.value)}></input>
            <label>Resumo</label>
            <textarea type="text" className="form-control" value={resumo} onChange={(evento) => setResumo(evento.target.value)}></textarea>
            <label>Editora</label>
            <select className="form-select" value={codEditora} onChange={tratarCombo}>
              {opcoes.map((opcao) => (
                <option key={opcao.value} value={opcao.value}>
                  {opcao.text}
                </option>
              ))}
            </select>
            <label>Autores (1 por linha)</label>
            <textarea type="text" className="form-control" value={autores} onChange={(evento) => setAutores(evento.target.value)}></textarea>
            <button type="submit" className="btn btn-primary d-block mt-3">
              Salvar Dados
            </button>
          </div>
        </form>
      </div>
    </main>
  );
};

export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  livro: Livro;
  autoresForm: string = '';
  editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {
    this.livro = new Livro('', 0, '', '', []);
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/lista');
    });
  }
}
<main class="container">
    <h1>Dados do Livro</h1>  
    <form (submit)="incluir()" ngNativeValidate>
      <div class="form-group">
        <label for="titulo">Título:</label>
        <input type="text" name="titulo" class="form-control" required [(ngModel)]="livro.titulo">
      </div>  
      <div class="form-group">
        <label for="resumo">Resumo:</label>
        <textarea name="resumo" class="form-control" [(ngModel)]="livro.resumo"></textarea>
      </div>  
      <div class="form-group">
        <label for="editora">Editora:</label>
        <select name="editora" class="form-select" required [(ngModel)]="livro.codEditora">
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>
      </div>  
      <div class="form-group">
        <label>Autores:</label>
        <textarea name="autores" class="form-control" [(ngModel)]="autoresForm"></textarea>
      </div>  
      <button type="submit" class="btn btn-primary d-block mt-3">Salvar</button>
    </form>
  </main>
